version: '3.3'

services:
  appTesis:
    image: postgres:13
    environment:
      - POSTGRES_DB=api_AppTesis
      - POSTGRES_USER=andres
      - POSTGRES_PASSWORD=dcandres123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80

  mysql:
        image: mysql:5
        environment:
            - MYSQL_DATABASE=servicesApp
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=admin
            - MYSQL_PORT=3306
        ports:
            - "3306:3306"
        volumes:
            - ./mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
            - MYSQL_ROOT_PASSWORD=admin
            - PMA_HOST=mysql
    ports:
            - 8080:80
